// Code generated by "stringer -type=DateFormat"; DO NOT EDIT.

package omni

import "fmt"

const _DateFormat_name = "MMDDDDMM"

var _DateFormat_index = [...]uint8{0, 4, 8}

func (i DateFormat) String() string {
	i -= 1
	if i >= DateFormat(len(_DateFormat_index)-1) {
		return fmt.Sprintf("DateFormat(%d)", i+1)
	}
	return _DateFormat_name[_DateFormat_index[i]:_DateFormat_index[i+1]]
}
