// Code generated by "stringer -type=SystemFeature"; DO NOT EDIT.

package omni

import "fmt"

const _SystemFeature_name = "NuVoConcertoNuVoEssentiaNuVoGrandConcertoRussoundHAIHiFiXanTechSpeakerCraftProficientDSCSecurity"

var _SystemFeature_index = [...]uint8{0, 12, 24, 41, 49, 56, 63, 75, 85, 96}

func (i SystemFeature) String() string {
	i -= 1
	if i >= SystemFeature(len(_SystemFeature_index)-1) {
		return fmt.Sprintf("SystemFeature(%d)", i+1)
	}
	return _SystemFeature_name[_SystemFeature_index[i]:_SystemFeature_index[i+1]]
}
