// Code generated by "stringer -type=TempFormat"; DO NOT EDIT.

package omni

import "fmt"

const _TempFormat_name = "FahrenheitCelsius"

var _TempFormat_index = [...]uint8{0, 10, 17}

func (i TempFormat) String() string {
	i -= 1
	if i >= TempFormat(len(_TempFormat_index)-1) {
		return fmt.Sprintf("TempFormat(%d)", i+1)
	}
	return _TempFormat_name[_TempFormat_index[i]:_TempFormat_index[i+1]]
}
