// Code generated by "stringer -type=TimeFormat"; DO NOT EDIT.

package omni

import "fmt"

const _TimeFormat_name = "TwelveTwentyFour"

var _TimeFormat_index = [...]uint8{0, 6, 16}

func (i TimeFormat) String() string {
	i -= 1
	if i >= TimeFormat(len(_TimeFormat_index)-1) {
		return fmt.Sprintf("TimeFormat(%d)", i+1)
	}
	return _TimeFormat_name[_TimeFormat_index[i]:_TimeFormat_index[i+1]]
}
